on:
  workflow_dispatch:
    inputs:
      Browsers:
        description: 'Browsers'
        required: true
        default: 'chrome'
        type: choice
        options:
        - chrome
        - firefox
        - edge
      Plateforme:
        description: 'Admin/LC'
        required: true
        default: 'Admin'
        type: choice
        options:
        - Admin
        - LC
      Environnement:
        description: 'Staging/preprod/prod'
        required: true
        default: 'Staging'
        type: choice
        options:
        - Staging
        - Preprod
        - Prod


jobs:
 Cypress-Test:
   runs-on: ubuntu-latest
   steps: 
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
           node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
         command: npx cypress run --browser chrome --config-file cypress/ConfigsFiles/Admin/admintool-staging.json --spec 'cypress/integration/Features/Admin/AddRoomsAndEquipements.feature'
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
         command: npm run generate-cucumber-report
