on:
  workflow_dispatch:
    inputs:
      Browsers:
        description: 'Browsers'
        required: true
        default: 'chrome'
        type: choice
        options:
        - chrome
        - firefox
        - edge
      Plateforme:
        description: 'Admin/Users'
        required: true
        default: 'Admin'
        type: choice
        options:
        - Admin
        - Users
      ConfigFiles:
        description: 'Config files to start tests'
        required: true
        default: 'admintool-staging.json'
        type: choice
        options:
        - admintool-staging.json
        - lc-staging.json
        - admintool-prod.json
        - lc-prod.json
      Features:
        description: 'Choose feature to run'
        required: true
        default: 'All'
        type: choice
        options:
        - All

jobs:
 Cypress-Test:
   name: Cypress tests
   runs-on: ubuntu-latest
   steps:            
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
           node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
         command: npx cypress run --browser ${{ inputs.Browsers }} --config-file cypress/ConfigsFiles/${{ inputs.Plateforme }}/${{ inputs.ConfigFiles }} --spec 'cypress/integration/Features/Users/Connexion.feature'
      - name: Generate Cucumber Report
        uses: cypress-io/github-action@v5
        if: always()
        with:
         command: npm run generate-cucumber-report
      - name: Generate XML Report
        uses: cypress-io/github-action@v5
        if: always()
        with:
         command: npm run postreport
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/cypress/results/combined-report.xml'
